#######################################################################
#                                                                     #
# Package: fullsibQTL                                                 #
#                                                                     #
# File: fullsib_perm.R                                                #
#                                                                     # 
# Contains:                                                           #
# summary.fullsib_perm                                                #
# plot.fullsib_perm                                                   #
#                                                                     #
# Written by Rodrigo Gazaffi                                          #
# Updated by Rodrigo Amadeu                                           #
# copyright (c) 2011, Rodrigo Gazaffi                                 #
# summary.fullsib_perm is based on summary.scanoneperm from qtl pkg   #
# plot.fullsib_perm    is based on plot.scanoneperm from qtl package  #
#                                                                     #
# First version: 09/30/2011 (american date format)                    #
# Last  version: 08/15/2017 (american date format)                    #
# License: GNU General Public License version 2 (June, 1991) or later #
#                                                                     #
#######################################################################

#######################################################################
## summary.fullsib_perm                                               #
## function that provides the threshold values, for differents alphas #
## by default it show 0.05, 0.10                                      #
## column one is the classical threshold by Churchill and Doerge, 1994#
## second columns and so, are modification by Chen and Storey, 2006   #
#######################################################################

## -------------------------
## summary.fullsib_perm

#' Returns the threshold obtained with permutation test
#' 
#' Gives the Threshold obtained with permutation test. It is used for both
#' \code{im_scan} and \code{cim_scan}, when \sQuote{n.perm} argument is higher
#' than 0.
#' 
#' It receives an object of class \emph{fullsib_perm} and apply for each column
#' a quantile function to calculate the thresholds, using default of function
#' \code{quantile} from \code{stats} package.
#' 
#' @param object An object of class \emph{fullsib_perm}, output of
#' \code{im_scan} and \code{cim_scan}, when permutation test is performed.
#' @param alpha Genome-wide significance levels.
#' @param verbose if TRUE print the heading information
#' @param \dots parameters to be passed.
#' 
#' @return It returns a matrix summarizing the results generated by permutation
#' test. In the rows each level of probabiliy defined by user is showed, by
#' default two rows is printed (alpha at 0.05 and 0.10). The number of columns
#' indicates the ordered highest peaks. If threshold value obtained for column
#' of \sQuote{peak.1} is considered, one is using the approach proposed by
#' Churchill and Doerge (1994). If \code{peaks.2} is used, it corresponds to
#' the approach proposed by Chen and Storey (2006).
#' @author Rodrigo Gazaffi \email{rgazaffi@@gmail.com}
#' @seealso 
#' \code{\link[fullsibQTL]{im_scan}}
#' \code{\link[fullsibQTL]{cim_scan}}
#' \code{\link[fullsibQTL]{plot.fullsib_perm}}
#' 
#' @references Chen, L., Storey, J.D. (2006) Relaxed Significance Criteria for
#' Linkage Analysis. Genetics 173: 2371-2381
#' 
#' Churchill, G.A., Doerge, R.W. (1994) Empirical Threshold Values for
#' Quantitative Trait Mapping. Genetics 138: 963-971
#' @keywords utilities
#' @examples
#' 
#'   \dontrun{
#'   data( "example_QTLfullsib" )
#' 
#'   fullsib <- create_fullsib( example_QTLfullsib,
#'                              list( LG1_final, LG2_final, LG3_final, LG4_final ), 
#'                              step = 0, map.function = "kosambi", condIndex = 3.5 ) 
#' 
#'   im_perm <- im_scan( example_QTLfullsib, pheno.col = 1, LOD = TRUE, n.perm = 1000,
#'                       write.perm = "perm_values.txt" ) 
#'   summary( im_perm )
#'   summary( im_perm, alpha = 0.05 )
#'   ## first peak: churchill and doerge (1994)
#'   ## second peak: chen and storey (2006)
#'   
#'   summary( im_perm, alpha = 0.05, verbose = FALSE )
#'   }
#' 
#' @export
#' @method summary fullsib_perm
summary.fullsib_perm <- function(object,
                                 alpha=c(0.05, 0.10), verbose=TRUE, ...)
{
  threshold <-  apply(object, 2, quantile, 1 - alpha, na.rm=T)

  if(length(alpha) == 1 && length(threshold) > 1)
    threshold <- t(threshold)
  
  threshold <- as.data.frame(threshold)
  colnames(threshold) <- colnames(object)
  rownames(threshold) <- round(alpha,2)
  
  if(verbose){
    cat(" Threshold considering", nrow(object), "permutations\n")
    if(ncol(object) == 2){
      cat(" First column indicates", sQuote("classical"), "threshold showed by Churchill and Doerge, 1994\n")
      cat(" Second column means threshold values suggested by Chen and Storey, 2006\n")
    }
  }
  threshold
}

#######################################################################
## plot_fullsib_perm                                                  #
## function that plots the distribution of values obtained by the     #
## permutation test. One can detail wich peak should be plot          #
#######################################################################

## -------------------------
## plot.fullsib_perm function

#' Plot the histogram of maximum values of permutation test
#' 
#' Plots the histogram of maximum values obtained with the permutation test.
#' The graphic can be done for each QTL peak
#' 
#' When permutation test is done, an empirical distribuition is obtained for
#' having a threshold for QTL mapping. However, we implemented the approach of
#' Chen and Storey (2006) for having a relaxed threshold values. As a result,
#' the object of class \emph{fullsib_perm} contains the distribution of two
#' highest peaks, each one can be assessed using the argument. If
#' \sQuote{peak=1} shows the classical permutation test present by Churchill
#' and Doerge (1994).
#' 
#' @param x An object of class \emph{fullsib_perm}, output of \code{im_scan} or
#' \code{cim_scan}.
#' @param peak QTL peak to be used to plot the histogram. Default is to use the
#' first peak. See details.
#' @param \dots Passed to the function \code{plot} when it is called. See
#' \code{\link{hist}} for more options to be included here.
#' 
#' @return A histogram showing the distribution of maximum values obtained on
#' each permutation test. \code{hist} function is used to do the plot.
#' 
#' @author Written by Karl Broman for \sQuote{plot.scanoneperm} from \pkg{qtl}
#' package and adapted by Rodrigo Gazaffi \email{rgazaffi@@gmail.com}
#' 
#' @seealso 
#' \code{\link[fullsibQTL]{im_scan}}
#' \code{\link[fullsibQTL]{cim_scan}}
#' \code{\link[fullsibQTL]{summary.fullsib_perm}}
#' \code{\link{hist}}
#' 
#' @references Chen, L., Storey, J.D. (2006) Relaxed Significance Criteria for
#' Linkage Analysis. \emph{Genetics} 173: 2371-2381
#' 
#' Churchill, G.A., Doerge, R.W. (1994) Empirical Threshold Values for
#' Quantitative Trait Mapping. \emph{Genetics} 138: 963-971.
#' @keywords plot
#' @examples
#' 
#'   \dontrun{
#'   data(example_QTLfullsib)
#' 
#'   fullsib <- create_fullsib( example_QTLfullsib,
#'                              list( LG1_final, LG2_final, LG3_final, LG4_final ), 
#'                              step = 0, map.function = "kosambi", condIndex = 3.5 ) 
#' 
#'   im.perm <- im_scan( fullsib, pheno.col = 1, LOD = TRUE, n.perm = 1000,
#'                       write.perm = "perm_values.txt" ) 
#'   plot( im.perm, peak = 1 ) ## churchill and doerge (1994)
#'   plot( im.perm, peak = 2 ) ## chen and storey (2006)
#'   }
#' 
#' @importFrom graphics hist par rug
#' @importFrom stats quantile
#' @export
#' @method plot fullsib_perm
plot.fullsib_perm <- function(x, peak=1, ...)
{

  x <- x[,peak]
  n.brk <- ceiling(2*sqrt(length(x)))
  xlim <- c(0,max(as.numeric(x), na.rm=TRUE))
  
  dots <- list(...)
  main <- ""
  xlab <- "maximum"
  
  if("breaks" %in% names(dots)) {
    if("main" %in% names(dots)) {
      if("xlab" %in% names(dots)) {
        hist(x, xlim=xlim, ...)
      }
      else {
        hist(x, xlim=xlim, xlab=xlab, ...)
      }
    }
    else {
      if("xlab" %in% names(dots)) {
        hist(x, xlim=xlim, main=main, ...)
      }
      else {
        hist(x, xlim=xlim, xlab=xlab, main=main, ...)
      }
    }
  }
  else {
    if("main" %in% names(dots)) {
      if("xlab" %in% names(dots)) {
        hist(x, breaks=n.brk, xlim=xlim, ...)
      }
      else {
        hist(x, breaks=n.brk, xlim=xlim, xlab=xlab, ...)
      }
    }
    else {
      if("xlab" %in% names(dots)) {
        hist(x, breaks=n.brk, xlim=xlim, main=main, ...)
      }
      else {
          hist(x, breaks=n.brk, xlim=xlim, xlab=xlab, main=main, ...)
        }
    }
  }
  
  rug(as.numeric(x))
}